export const MOCK_CASES = [
  {
    id: 1,
    type: "person",
    name: "Ana García",
    age: 8,
    location: "Lima, Miraflores",
    date: "2026-06-20",
    status: "active",
    description: "Niña de 8 años, cabello negro lacio, ojos marrones.",
    image: null,
    assignedTo: 3,
  },
  {
    id: 2,
    type: "pet",
    name: "Toby",
    breed: "Labrador dorado",
    location: "Lima, San Isidro",
    date: "2026-06-22",
    status: "active",
    description: "Labrador de 3 años, collar rojo con placa.",
    image: null,
    assignedTo: 3,
  },
  {
    id: 3,
    type: "person",
    name: "Roberto Díaz",
    age: 72,
    location: "Lima, Surco",
    date: "2026-06-15",
    status: "found",
    description: "Adulto mayor, cabello blanco, usa lentes.",
    image: null,
    assignedTo: null,
  },
  {
    id: 4,
    type: "pet",
    name: "Luna",
    breed: "Siamés",
    location: "Lima, Barranco",
    date: "2026-06-24",
    status: "active",
    description: "Gata siamesa, ojos azules, sin collar.",
    image: null,
    assignedTo: null,
  },
  {
    id: 5,
    type: "person",
    name: "Sofía Mendoza",
    age: 16,
    location: "Callao",
    date: "2026-06-25",
    status: "active",
    description: "Adolescente, cabello castaño con mechas, 1.60m.",
    image: null,
    assignedTo: 3,
  },
];

export const STATS = {
  admin: {
    totalCases: 124,
    activeCases: 87,
    foundCases: 37,
    volunteers: 23,
    persons: 81,
    pets: 43,
  },
  citizen: {
    myReports: 3,
    activeReports: 2,
    resolvedReports: 1,
  },
  volunteer: {
    assigned: 5,
    resolved: 12,
    pending: 3,
  },
};
